version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql


  app:
    build: './app/'
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always
